# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('image_url', models.FileField(blank=True, null=True, upload_to='')),
                ('start_price', models.CharField(max_length=20)),
                ('end_price', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('buy_or_sell', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Client')),
            ],
            options={
                'db_table': 'proposal',
            },
        ),
    ]
