# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-17 21:08
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('projects', '0002_auto_20180318_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
