# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180113_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
